name: 'whisper'
description: 'A sample command-line application.'
version: '1.0.0'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  flutter_web_plugins: 
    sdk: 'flutter'
  path: '^1.8.0'
  ffi: '^2.1.2'
  plugin_platform_interface: '^2.0.2'
  general_lib: '^0.0.44'
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.24.0'
dependency_overrides: 
  pointycastle: '3.8.0'
funding: 
  - 'https://github.com/sponsors/azkadev'
